package servlets.model;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Created by alex323glo on 24.02.18.
 */
@MappedSuperclass
public class IdAutoGeneratedEntity {

    @Id
    @GeneratedValue
    private int id;

    public IdAutoGeneratedEntity() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
