package servlets.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * User model entity class.
 *
 * @author alex323glo
 * @version 1.0
 */
@Entity
@Table(name = "users")
public class User extends IdAutoGeneratedEntity {

    @Column(nullable = false)
    private String email;

    @Column(nullable = false)
    private String password;

    public User() {
    }

    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }


    private User(int id, String email, String password) {
        this.setId(id);
        this.email = email;
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "{" +
                "\"id\":" + getId() +
                ", \"email\":\"" + email + '\"' +
                ", \"password\":\"" + password + '\"' +
                '}';
    }

    @Override
    public User clone() {
        return new User(getId(), email, password);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (getEmail() != null ? !getEmail().equals(user.getEmail()) : user.getEmail() != null) return false;
        if (user.getId() != getId()) return false;

        return getPassword() != null ? getPassword().equals(user.getPassword()) : user.getPassword() == null;
    }

    @Override
    public int hashCode() {
        return getId();
    }
}
